### ISSUE TITLE
SQLSTATE[HY000]: General error: 17 database schema has changed

### ISSUE THREAD

**Issue by cvuorinen** [liip/LiipFunctionalTestBundle#109]
This is kind of a strange error so I don't really know if this is related to this bundle or Doctrine or PDO or the way PDO uses the SQLite API or SQLite itself or what, but I get this error when running tests that extend Liip\FunctionalTestBundle\Test\WebTestCase. It only happens on the very first test that uses the db, other tests after that execute correctly. And it happens only after cache has been cleared, if the db files are in cache then there is no error.

On local dev machines we can of course run again if we get this error, but our Jenkins build clears the cache before running the tests, so our build always fails :(

Anyone else ever had this issue or have any idea what could be causing this?

**Comment by inanzzz** [comment]
In my case, it was cache issue.  I had job below in my `build.xml` which caused the problem.

```
    <target name="prepare">
        <exec executable="app/console">
            <arg value="cache:clear"/>
            <arg value="--env=test"/>
        </exec>
    </target>
```

**Comment by alexislefebvre** [comment]
@cvuorinen can you reproduce this bug with the current version? Can we close this issue? Thanks.

**Comment by cvuorinen** [comment]
Haven't seen that error for a long time and we are no longer using the sleep(1) call so you can close it. Not really sure what caused it in the first place, but has not been an issue for us lately.

**Comment by advancingu** [comment]
I ran into this issue just now. It only occurs if I run our entire 500+ test / 5000+ assertion test suite and only for a single test case where we use `client` to test requests to our API. The difference of this testcase to other similar cases is that I am calling `loadFixtures()` with an empty array instead of with a fixtures class like in all the other working API tests.
What is also strange is that if I run only the tests of the test class containing this failing test, the test doesn't fail (the failing test is the last of about 20 tests in this class). Neither does it fail if I run tests for the entire bundle. It only fails when I run the entire test suite (takes about 30 minutes).
Adding `sleep(1);` to immediately after `loadFixtures([]);` doesn't fix the failing test.

**Comment by advancingu** [comment]
After some more testing it turned out that the root issue was that there was a `loadFixtures([FixturesClass])` in the `setUp()` method and then inside the test the first call was to `loadFixtures([])` which apparently was too quick of a change for SQlite to catch up. Putting a `sleep` between those two calls probably would have helped but I simply fixed the issue now by getting rid of the `loadFixtures()` call in `setUp()` and having each test load the required fixtures individually.

**Comment by alexislefebvre** [comment]
@advancingu I had the same error recently when using a repository to fetch some data or calling `loadFixtures()` 2 times in the same test (I don't remember exactly), I'll try to provide a failing example.

**Comment by alexislefebvre** [comment]
Here is a PR with a failing test while it looks normal: https://github.com/alexislefebvre/LiipFunctionalTestBundle/pull/24

Maybe this code was not a good idea though:

    $this->client = static::makeClient();
    
    $em = $this->client->getContainer()
        ->get('doctrine.orm.entity_manager');

**Comment by twifty** [comment]
I have also encountered this error. For me it happens each time a test loads a different set of fixtures.

Narrowing it down, the `loadFixtures` method switches the database, but I'm guessing, the connection has stored procedures for that database. The only solution I could come up with is to close the connection before the fixtures are loaded.

**Comment by rvadym** [comment]
It is required to close and reopen connection if you change SQLite database file or database schema somehow.

**Comment by alexislefebvre** [comment]
@rvadym Do you have any code to *close and reopen connection* that you can share? Is it something that may be automated?

**Comment by rvadym** [comment]
@alexislefebvre Sorry, just found your question. Hope it will help somebody else.

Close:
```
$connection = $this->getContainer()->get('doctrine.orm.entity_manager')->getConnection();
if (null !== $connection) {
    $connection->close();
}
```

And Symfony will open connection automatically after you close it I guess.

**Comment by lpitteloud** [comment]
I solved this error by applying this configuration : 

`cache_sqlite_db: true`

Hope it will help some of you !

**Comment by lsmith77** [comment]
https://github.com/liip/LiipFunctionalTestBundle/pull/318
