### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such table

### ISSUE THREAD

**Issue by guidokritz** [liip/LiipFunctionalTestBundle#160]
Hi!

I'm trying to run my tests using SQLite as described in the documentation for this bundle and I get this error after each attempt to load a fixture:

SQLSTATE[HY000]: General error: 1 no such table NameOfTheTable

If i manually try to drop/create the schema using --env=test if works just fine. Even if I run those commands in the test before calling the loadFixtures() method they drop and create the schema successfully. But then when the fixtures are loaded I still get the same error.

Any idea how to fix this?

I'm using liip/functional-test-bundle 1.2.2, doctrine/dbal 2.3.5 and doctrine/doctrine-fixtures-bundle 2.2.0

Thanks!

EDIT: Forget to mention that everything works fine if I run my tests using MySQL instead of SQLite.

**Comment by lsmith77** [comment]
It could be related to the fact that you are using camel case table names .. not sure if SQLite likes this ..

**Comment by lsmith77** [comment]
ping

**Comment by guidokritz** [comment]
I'm not too familiar with SQLite, but I don't think there're issues with case in tables names. Also Doctrine is handling the tables creation and queries execution. I'm pretty sure it would take care of that kind of compatibility issues if there were any.

**Comment by Hywan** [comment]
@lsmith77 SQLite has no issue with camel case table names.

**Comment by lsmith77** [comment]
functional test bundle copies the sqlite files after creating the schema and running the fixtures but before running the tests, so that it can restore them in the next test using the same schema/fixture combination. maybe something is going wrong with copying the files around. does the issue also happen if you run the test one at a time?

**Comment by edhgoose** [comment]
I'm having exactly the same issue.

I've disabled the `cache_sqlite_db` to try and ensure nothing strange is happening there. So far, it appears that the SQL all executes fine but when I check the database it is 0bytes.

I've found that in Doctrine's SchemaTool (here: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/SchemaTool.php#L93) I can modify it to dump a copy of all the SQL being executed, dump it into a file and then execute that against a SQLite database without trouble.

I'm only running one test at the moment too.

**Comment by edhgoose** [comment]
To further add to this, I'm finding that the Symfony2 command:

    doctrine:schema:create --env=test

...is doing nothing.

It's not creating the database at all. It says it is:

````
doctrine:schema:create --env=test
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
Database schema created successfully!

Process finished with exit code 0 at 18:40:53.
Execution time: 23,301 ms.
````

But there is no db file that I can see.

**Comment by edhgoose** [comment]
Me again...

I've resolved the issue on my side. Hopefully this will help you too @guidokritz?

The issue was our doctrine configuration has two slaves configured on our live environment. Our test environment inherited from our production environment, and therefore the slaves were passed through.

Something to do with the Doctrine configuration meant that the `path` option wasn't passed through to the [DBAL Connection.php](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L205) in the `$params` option. This then cascaded down (particularly to (this line which required the path)[https://github.com/doctrine/dbal/blob/2.2/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php#L114] and meant nothing seemed to work.

I've since changed my configuration to separate the configuration of our slaves, and this is now done in a production only configuration. I found commenting out all the slave configuration (including `slaves:`) worked for me.

Hope it helps you.

**Comment by guidokritz** [comment]
Great catch @edhgoose! Apparently that was the issue.
I moved my slaves configuration from config.yml to config_prod.yml and now tests are running with SQLite with no errors!
Thanks for your help.
It would be nice to have this documented.

**Comment by edhgoose** [comment]
Thanks! I'm not sure who's responsibility the bug is. My gut is it's a DoctrineBundle thing. Maybe they should document this / fix it if is not intended behaviour, but I'm not really sure. 

@lsmith77, I'm happy to raise a bug somewhere or write some docs for this Bundle - what would you recommend?

**Comment by lsmith77** [comment]
for now maybe add a small comment into the docs of this Bundle and then also submit a bug to the DoctrineBundle. but not sure if they will see it as a bug

**Comment by lsmith77** [comment]
ping

**Comment by edhgoose** [comment]
Apologies, totally forgot. PR #164 is raised.

**Comment by lsmith77** [comment]
thx!
