### ISSUE TITLE
Conflicts with sonata admin bundle 2.3

### ISSUE THREAD

**Issue by uirapuru** [liip/LiipFunctionalTestBundle#178]
So, I installed 1.3-dev version of LiipFunctionalTestBundle and after reloading project got this exception:

`
FileLoaderLoadException: Catchable Fatal Error: Argument 1 passed to Sonata\AdminBundle\Admin\Admin::setValidator() must implement interface Symfony\Component\Validator\ValidatorInterface, instance of Liip\FunctionalTestBundle\Validator\DataCollectingValidator given, called in /var/www/app.gyman/app/cache/dev/appDevDebugProjectContainer.php on line 713 and defined in /var/www/app.gyman/app/config/. (which is being imported from "/var/www/app.gyman/app/config/routing.yml").
`

**Comment by lsmith77** [comment]
I think this might be caused due to changes in core. Please verify if we can safely change the interface the DataCollectingValidator implements:
https://github.com/liip/LiipFunctionalTestBundle/blob/master/Validator/DataCollectingValidator.php#L19

**Comment by sc0rp10** [comment]
Any news?

**Comment by faboo03** [comment]
I have the same issue and for what I understand : 
Sonata\AdminBundle\Admin\Admin::setValidator() required Symfony\Component\Validator\ValidatorInterface that is deprecated since SF 2.5. SonataAdmin should require Symfony\Component\Validator\Validator\ValidatorInterface instead... 
Maybe it's something that need to be corrected in SonataAdmin...

**Comment by Yonn-Trimoreau** [comment]
Same here... :'(

**Comment by infobeans-rohits** [comment]
Facing the same. Any Update?

**Comment by syabro** [comment]
+1

**Comment by lsmith77** [comment]
anyone have time to work on a PR?

**Comment by batsuev** [comment]
+1

**Comment by sc0rp10** [comment]
@lsmith77 maybe I can PR, but how do I check that my fixes will be correct? Bundle doesn't have any tests.

**Comment by focusshifter** [comment]
+1

**Comment by Snawoot** [comment]
+1

**Comment by Icewild** [comment]
+1

**Comment by lsmith77** [comment]
create some? :)

**Comment by faboo03** [comment]
Even if it's not the solution, moving sonata-projet/admin-bundle to "dev-master" seems to correct the problem...

**Comment by lsmith77** [comment]
that sounds surprising or @rande did you fix something there?

**Comment by rande** [comment]
The validator namespace from the symfony has been changed.

So we have check like this:

```
    /**
     * {@inheritdoc}
     */
    public function setValidator($validator)
    {
        // TODO: Remove it when bumping requirements to SF 2.5+
        if (!$validator instanceof ValidatorInterface && !$validator instanceof LegacyValidatorInterface) {
            throw new \InvalidArgumentException('Argument 1 must be an instance of Symfony\Component\Validator\Validator\ValidatorInterface or Symfony\Component\Validator\ValidatorInterface');
        }

        $this->validator = $validator;
    }
```

So maybe, the LiipFunctionalTestBundle does not implement the correct interface depends on the Symfony version installed.

**Comment by tackerm** [comment]
I think @faboo03 is correct. The LiipFunctionalTestBundle uses the new, correct interface, while the SonataAdminBundle (2.3.7) still requires the deprecated Symfony\Component\Validator\ValidatorInterface.

If I update Sonata\AdminBundle\Admin\Admin to require the new Symfony\Component\Validator\Validator\ValidatorInterface instead (and remove the call to getMetadataFactory() from line 1317), everything works fine for me. This seems to be fixed in the master branch of SonataAdminBundle, but not in 2.3.

**Comment by alexislefebvre** [comment]
I added some tests in my fork, click on the badges here to see the results: https://github.com/alexislefebvre/LiipFunctionalTestBundle/blob/master/README.md

This is just the beginning, the test environment works but it lacks tests.

**Comment by lsmith77** [comment]
I would suggest to open a PR early .. then others can help with adding more tests.

**Comment by alexislefebvre** [comment]
@lsmith77 Ok. I'll open a PR not later than in 3 weeks.

**Comment by lsmith77** [comment]
should be fixed now

**Comment by alexislefebvre** [comment]
@lsmith77 Can you please publish a new release of this bundle? I still have errors with SonataAdminBundle.
