### ISSUE TITLE
How to load fixture yml files which are outside a bundle? 

### ISSUE THREAD

**Issue by Kwadz** [liip/LiipFunctionalTestBundle#301]
To load the fixtures, I use:

```
$fixtures = $this->loadFixtureFiles(array(
    '../../Resources/fixtures/orm/processor.yml',
));
```

and I get: `A resource name must start with @ ("../../DataFixtures/ORM/processor.yml" given).`

So, how to load yml files which are outside a bundle? 
In this case where should be located the `DataFixtures/ORM/` directory?

**Comment by alexislefebvre** [comment]
It looks like the error message does not come from LiipFunctionalTestBundle. Can you please give the complete error backtrace?

**Comment by Kwadz** [comment]
To reproduce the error:

1. Install new Symfony project
2. Install LiipFunctionalTestBundle: `composer require --dev liip/functional-test-bundle`
3. Install AliceBundle: `composer require --dev hautelook/alice-bundle:~1.2`
4. Install DoctrineFixturesBundle: `composer require --dev doctrine/doctrine-fixtures-bundle`
5. Add the following code:

```
use Liip\FunctionalTestBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testLiip() {
        $fixtures = $this->loadFixtureFiles(array(
            '../../DataFixtures/ORM/YetAnotherObjectData.yml',
        ));
    }
}
``` 

Stacktrace:

```
A resource name must start with @ ("../../DataFixtures/ORM/YetAnotherObjectData.yml" given).
 /Users/richard/dev/my_sf3_project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:213
 /Users/richard/dev/my_sf3_project/vendor/liip/functional-test-bundle/Test/WebTestCase.php:524
 /Users/richard/dev/my_sf3_project/vendor/liip/functional-test-bundle/Test/WebTestCase.php:562
 /Users/richard/dev/my_sf3_project/tests/AppBundle/Controller/DefaultControllerTest.php:22
```

**Comment by alexislefebvre** [comment]
Thanks. The error comes from these lines: https://github.com/liip/LiipFunctionalTestBundle/blob/dc7eb1b2fbb2f2c508c121f7ee0bb4ed1a96128b/Test/WebTestCase.php#L518-L525

The first condition `$path[0] !== '@'` is met since the path you provide doesn't start with `@`. But it seems that the second condition `file_exists($path) === true` fails. It looks like this is the reason that `locateResource()` is called instead of being skipped by the `continue;`.

I don't know what is the base directory that will be used when calling `file_exists()`.

Can you please try some other paths, like `'../../../DataFixtures/ORM/YetAnotherObjectData.yml'` or `'../DataFixtures/ORM/YetAnotherObjectData.yml'`? I'm pretty sure that if `file_exists($path)` can find the file then it will be loaded succesfully.

**Comment by Kwadz** [comment]
@alexislefebvre the base directory is where the test is located, for exemple:

my-project/tests/AppBundle/Controller/
