### ISSUE TITLE
Question: 3.4.0 Release

### ISSUE THREAD

**Issue by steffenbrand** [liip/LiipFunctionalTestBundle#559]
Hi, I'm currently using the bundle with dev-master (6024b27a6fac223def4a502fbf6d19775d279fb2) and Symfony 5. I'm not experiencing any problems, so I wanted to ask if there are still issues to solve that I'm not aware of. If not I would be very happy if you could tag a 3.4.0 ;) Thanks a lot for your bundle!

**Comment by alexislefebvre** [comment]
We broke the support of `paratest` for this alpha release. Restoring it is harder than expected: https://github.com/liip/LiipFunctionalTestBundle/pull/557

---

On a side note, I suggest you to use the `3.4.0-alpha1` tag in composer instead of `dev-master`, so that it will always install the same version. :wink:

**Comment by alexislefebvre** [comment]
Please try the last release: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/4.0.0-alpha1

**Comment by steffenbrand** [comment]
4.0.0-alpha1 works fine with all our tests :+1:

**Comment by alexislefebvre** [comment]
Thanks! Here is the stable release: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/4.0.0
